In [6]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [7]:
df = pd.read_csv("input/Khảo sát tâm tư các sĩ tử chuẩn bị thi THPTQG.csv")
df.head()

,Dấu thời gian,Bạn hiện đang là học sinh lớp mấy?,Bạn đến từ miền nào? (Bao gồm các khu vực hải đảo tương ứng),Bạn giỏi những môn nào trong những môn bạn dự tính thi THPTQG?,Bạn không giỏi những môn nào trong những môn bạn dự tính thi THPTQG?,Điểm trung bình trong lớp của bạn như thế nào ở học kỳ gần nhất?,"Bạn dự định sẽ thi những tổ hợp nào? \n(Nếu chưa quyết định, em hãy điền tổ hợp mà em đang có xu hướng chọn cao nhất nhé.)",Bạn dự đoán điểm tổ hợp của bạn sẽ trong khoảng nào?,Mục đích bạn thi THPTQG là gì?,"Giả sử bạn vừa biết điểm thi tốt nghiệp THPTQG, bạn muốn biết điều gì về kết quả của mình?","Ngoài những mong muốn trên, bạn còn khao khát điều gì khác khi cầm tờ kết quả trên tay? (Ví dụ: Muốn biết mình có thuộc Top 100 của tỉnh không, hay muốn so sánh điểm với bạn bè một cách ẩn danh...)"
0,2026/03/24 7:09:52 CH GMT+7,Lớp 12,Miền Nam (bao gồm Đông Nam Bộ và Đồng bằng sôn...,NaN,NaN,[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn""",NaN
1,2026/03/24 10:27:40 CH GMT+7,Lớp 11,Miền Nam (bao gồm Đông Nam Bộ và Đồng bằng sôn...,NaN,NaN,[8.0 - 9.0),A01,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn"";So sánh tổ...",em mong muốn được vỡ oà cảm xúc sau những chặn...
2,2026/03/24 10:28:35 CH GMT+7,Lớp 12,Miền Nam (bao gồm Đông Nam Bộ và Đồng bằng sôn...,NaN,NaN,[8.0 - 9.0),D01 A01,[18 - 21),Xét tuyển bằng điểm thi THPTQG,"Xác suất ""an toàn""",Biết mình đậu hay ki
3,2026/03/25 5:50:08 CH GMT+7,Thí sinh tự do,"Miền Trung (bao gồm Bắc Trung Bộ, Duyên hải Na...",NaN,NaN,[9.0 - 10.0],A00,[27 - 30),Lấy điểm để đi du học hoặc xét tuyển riêng.,Phân tích phổ điểm,Nụ cười của cha mẹ
4,2026/03/26 11:29:09 SA GMT+7,Cựu học sinh / sinh viên (Đã tốt nghiệp THPT),"Miền Trung (bao gồm Bắc Trung Bộ, Duyên hải Na...",Toán (Đại số / Giải tích);Hóa học,Ngữ văn;Tiếng Anh;Sinh học,[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,Phân tích phổ điểm;So sánh tổ hợp,NaN

In [8]:
df.columns

Index(['Dấu thời gian', 'Bạn hiện đang là học sinh lớp mấy?',
       'Bạn đến từ miền nào? (Bao gồm các khu vực hải đảo tương ứng)',
       'Bạn giỏi những môn nào trong những môn bạn dự tính thi THPTQG?',
       'Bạn không giỏi những môn nào trong những môn bạn dự tính thi THPTQG?',
       'Điểm trung bình trong lớp của bạn như thế nào ở học kỳ gần nhất?',
       'Bạn dự định sẽ thi những tổ hợp nào? \n(Nếu chưa quyết định, em hãy điền tổ hợp mà em đang có xu hướng chọn cao nhất nhé.)',
       'Bạn dự đoán điểm tổ hợp của bạn sẽ trong khoảng nào?',
       'Mục đích bạn thi THPTQG là gì?',
       'Giả sử bạn vừa biết điểm thi tốt nghiệp THPTQG, bạn muốn biết điều gì về kết quả của mình?',
       'Ngoài những mong muốn trên, bạn còn khao khát điều gì khác khi cầm tờ kết quả trên tay? (Ví dụ: Muốn biết mình có thuộc Top 100 của tỉnh không, hay muốn so sánh điểm với bạn bè một cách ẩn danh...)  '],
      dtype='str')

# Mã hóa các câu trả lời

# B1, ở câu "Bạn hiện đang là học sinh lớp mấy?",
# - Đổi tên cột thành "Loại đối tượng"
# - Gộp chung "Cựu học sinh / sinh viên (Đã tốt nghiệp THPT)" với "Thí sinh tự do" thành "Đã tốt nghiệp THPT"
# - Loại bỏ câu trả lời "Cha mẹ", "Thầy cô", và những đáp án khác


# B2, ở câu "Bạn đến từ miền nào? (Bao gồm các khu vực hải đảo tương ứng)"
# - Đổi tên cột thành "Địa điểm" (Chỉ mang tính chất hình thức nên có thể bỏ sau đó


# B3, ở câu "Bạn giỏi những môn nào trong những môn bạn dự tính thi THPTQG?", Đổi tên cột thành "Các môn giỏi"


# B4, ở câu "Bạn giỏi những môn nào trong những môn bạn dự tính thi THPTQG?", Đổi tên cột thành "Các môn không giỏi"


# B5, ở câu "Bạn dự đoán điểm tổ hợp của bạn sẽ trong khoảng nào?", đổi tên cột thành "Điểm dự đoán"


# B6, ở câu "Bạn dự định sẽ thi những tổ hợp nào? \n(Nếu chưa quyết định, em hãy điền tổ hợp mà em đang có xu hướng chọn cao nhất nhé.)", đổi tên cột thành "Tổ hợp dự định"


# B7, ở câu "Mục đích bạn thi THPTQG là gì?", đổi tên cột thành "Mục đích"


# B8, ở câu "Giả sử bạn vừa biết điểm thi tốt nghiệp THPTQG, bạn muốn biết điều gì về kết quả của mình?", đổi tên cột thành "Mục đích chính"


# B9, ở câu "Ngoài những mong muốn trên, bạn còn khao khát điều gì khác khi cầm tờ kết quả trên tay? (Ví dụ: Muốn biết mình có thuộc Top 100 của tỉnh không, hay muốn so sánh điểm với bạn bè một cách ẩn danh...)  ", đổi tên cột thành "Mục đích phụ"

In [9]:
import pandas as pd

# =========================
# 1. Standardize column names
# =========================
df = df.rename(columns={
    "Bạn hiện đang là học sinh lớp mấy?": "doi_tuong",
    "Bạn đến từ miền nào? (Bao gồm các khu vực hải đảo tương ứng)": "dia_diem",
    "Bạn giỏi những môn nào trong những môn bạn dự tính thi THPTQG?": "mon_gioi",
    "Bạn không giỏi những môn nào trong những môn bạn dự tính thi THPTQG?": "mon_yeu",
    "Bạn dự đoán điểm tổ hợp của bạn sẽ trong khoảng nào?": "diem_du_doan",
    "Điểm trung bình trong lớp của bạn như thế nào ở học kỳ gần nhất?": "diem_gan_nhat",
    "Bạn dự định sẽ thi những tổ hợp nào? \n(Nếu chưa quyết định, em hãy điền tổ hợp mà em đang có xu hướng chọn cao nhất nhé.)": "to_hop_du_dinh",
    "Mục đích bạn thi THPTQG là gì?": "muc_dich",
    "Giả sử bạn vừa biết điểm thi tốt nghiệp THPTQG, bạn muốn biết điều gì về kết quả của mình?": "muc_tieu_chinh",
    "Ngoài những mong muốn trên, bạn còn khao khát điều gì khác khi cầm tờ kết quả trên tay? (Ví dụ: Muốn biết mình có thuộc Top 100 của tỉnh không, hay muốn so sánh điểm với bạn bè một cách ẩn danh...)  ": "muc_tieu_phu"
})



# =========================
# 2. Filter valid respondents
# =========================
valid_groups = [
    "Lớp 10",
    "Lớp 11",
    "Lớp 12",
    "Thí sinh tự do",
    "Cựu học sinh / sinh viên (Đã tốt nghiệp THPT)"
]

df = df[df["doi_tuong"].isin(valid_groups)]



# =========================
# 3. Grouping target population
# =========================
df["doi_tuong"] = df["doi_tuong"].replace({
    "Thí sinh tự do": "Đã tốt nghiệp THPT",
    "Cựu học sinh / sinh viên (Đã tốt nghiệp THPT)": "Đã tốt nghiệp THPT"
})


# =========================
# 4. Feature engineering (optional semantic cleaning)
# =========================
# (giữ raw text, chuẩn hóa câu trả lời)
df["dia_diem"] = df["dia_diem"].replace({
    "Miền Bắc (bao gồm Trung du và miền núi Bắc Bộ, và Đồng bằng sông Hồng)" : "Miền Bắc",
    "Miền Trung (bao gồm Bắc Trung Bộ, Duyên hải Nam Trung Bộ, và Tây Nguyên)" : "Miền Trung", 
    "Miền Nam (bao gồm Đông Nam Bộ và Đồng bằng sông Cửu Long)" : "Miền Nam"
}).astype("category")



# =========================
# 5. Drop non-informative respondents (optional rule-based filtering)
# =========================
df = df[~df["doi_tuong"].isin(["Cha mẹ", "Thầy cô"])]




# =========================
# Resulting dataset ready for analysis
# =========================
clean_df = df.copy()

clean_df.head(10)

,Dấu thời gian,doi_tuong,dia_diem,mon_gioi,mon_yeu,diem_gan_nhat,to_hop_du_dinh,diem_du_doan,muc_dich,muc_tieu_chinh,muc_tieu_phu
0,2026/03/24 7:09:52 CH GMT+7,Lớp 12,Miền Nam,NaN,NaN,[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn""",NaN
1,2026/03/24 10:27:40 CH GMT+7,Lớp 11,Miền Nam,NaN,NaN,[8.0 - 9.0),A01,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn"";So sánh tổ...",em mong muốn được vỡ oà cảm xúc sau những chặn...
2,2026/03/24 10:28:35 CH GMT+7,Lớp 12,Miền Nam,NaN,NaN,[8.0 - 9.0),D01 A01,[18 - 21),Xét tuyển bằng điểm thi THPTQG,"Xác suất ""an toàn""",Biết mình đậu hay ki
3,2026/03/25 5:50:08 CH GMT+7,Đã tốt nghiệp THPT,Miền Trung,NaN,NaN,[9.0 - 10.0],A00,[27 - 30),Lấy điểm để đi du học hoặc xét tuyển riêng.,Phân tích phổ điểm,Nụ cười của cha mẹ
4,2026/03/26 11:29:09 SA GMT+7,Đã tốt nghiệp THPT,Miền Trung,Toán (Đại số / Giải tích);Hóa học,Ngữ văn;Tiếng Anh;Sinh học,[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,Phân tích phổ điểm;So sánh tổ hợp,NaN
5,2026/03/26 11:40:45 SA GMT+7,Đã tốt nghiệp THPT,Miền Nam,Vật lý;Hóa học,Toán (Đại số / Giải tích);Toán (Hình học);Tiến...,[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn"";Thứ hạng ư...",NaN
6,2026/03/26 12:43:13 CH GMT+7,Lớp 10,Miền Bắc,Hóa học;Sinh học,Toán (Đại số / Giải tích);Toán (Hình học);Ngữ ...,[8.0 - 9.0),A00,[27 - 30),Khác,Thứ hạng ước tính;Phân tích phổ điểm,Muốn biết có đứng top 10 toàn quốc không?
7,2026/03/26 1:59:22 CH GMT+7,Đã tốt nghiệp THPT,Miền Nam,NaN,Toán (Đại số / Giải tích);Toán (Hình học);Ngữ ...,[6.0 - 7.0),"A01,C01",[18 - 21),Xét tuyển bằng điểm thi THPTQG,"Xác suất ""an toàn""",NaN
8,2026/03/26 7:19:06 CH GMT+7,Đã tốt nghiệp THPT,Miền Nam,Toán (Đại số / Giải tích);Vật lý;Tin học,Tiếng Anh,[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Xác suất ""an toàn""",Có
9,2026/03/26 7:33:47 CH GMT+7,Đã tốt nghiệp THPT,Miền Nam,Toán (Đại số / Giải tích);Toán (Hình học);Ngữ ...,Toán (Đại số / Giải tích);Toán (Hình học);Tiến...,[8.0 - 9.0),"B00, D01",[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn"";So sánh tổ...",NaN

In [10]:
clean_df["valid"] = True

# Tiền xử lý dữ liệu

## Xử lý dữ liệu môn học

In [11]:
valid_subjects = [
    "Toán (Đại số / Giải tích)",
    "Toán (Hình học)",
    "Ngữ văn",
    "Tiếng Anh",
    "Vật lý",
    "Hóa học",
    "Sinh học",
    "Lịch sử",
    "Địa lý",
    "GDKT&PL (Hoặc GDCD)",
    "Tin học",
    "Công nghệ công nghiệp",
    "Công nghệ nông nghiệp"
]


valid_subjects_set = set(valid_subjects)

In [12]:
# B1: Tách chuỗi
def normalize_subject(x):
    if pd.isna(x):
        return []
    
    return [
        val.strip() for val in str(x).split(";") if val.strip()
    ]

clean_df["mon_gioi"] = clean_df["mon_gioi"].apply(normalize_subject)
clean_df["mon_yeu"] = clean_df["mon_yeu"].apply(normalize_subject)

In [13]:
# B2: Kiểm tra tính hợp lệ

# 0. Khởi tạo tất cả đều là True
clean_df["valid"] = True

# 1. Kiểm tra môn lạ (Out of bounds)
# Nếu mon_gioi hoặc mon_yeu chứa bất kỳ phần tử nào không nằm trong valid_subjects_set
def has_invalid(subject_list):
    return any(s for s in subject_list if s not in valid_subjects_set)

invalid_gioi_mask = clean_df["mon_gioi"].apply(has_invalid)
invalid_yeu_mask = clean_df["mon_yeu"].apply(has_invalid)

## Kiểm tra trùng môn

In [14]:
def has_conflict(row):
    return not set(row["mon_gioi"]).isdisjoint(set(row["mon_yeu"]))

conflict_mask = clean_df.apply(has_conflict, axis=1)


# --- GÁN TRỰC TIẾP ---
# Chỉ cần vi phạm 1 trong các mask trên, valid sẽ thành False
clean_df.loc[invalid_gioi_mask | invalid_yeu_mask | conflict_mask, "valid"] = False

In [15]:
clean_df.head(10)

,Dấu thời gian,doi_tuong,dia_diem,mon_gioi,mon_yeu,diem_gan_nhat,to_hop_du_dinh,diem_du_doan,muc_dich,muc_tieu_chinh,muc_tieu_phu,valid
0,2026/03/24 7:09:52 CH GMT+7,Lớp 12,Miền Nam,[],[],[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn""",NaN,True
1,2026/03/24 10:27:40 CH GMT+7,Lớp 11,Miền Nam,[],[],[8.0 - 9.0),A01,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn"";So sánh tổ...",em mong muốn được vỡ oà cảm xúc sau những chặn...,True
2,2026/03/24 10:28:35 CH GMT+7,Lớp 12,Miền Nam,[],[],[8.0 - 9.0),D01 A01,[18 - 21),Xét tuyển bằng điểm thi THPTQG,"Xác suất ""an toàn""",Biết mình đậu hay ki,True
3,2026/03/25 5:50:08 CH GMT+7,Đã tốt nghiệp THPT,Miền Trung,[],[],[9.0 - 10.0],A00,[27 - 30),Lấy điểm để đi du học hoặc xét tuyển riêng.,Phân tích phổ điểm,Nụ cười của cha mẹ,True
4,2026/03/26 11:29:09 SA GMT+7,Đã tốt nghiệp THPT,Miền Trung,"[Toán (Đại số / Giải tích), Hóa học]","[Ngữ văn, Tiếng Anh, Sinh học]",[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,Phân tích phổ điểm;So sánh tổ hợp,NaN,True
5,2026/03/26 11:40:45 SA GMT+7,Đã tốt nghiệp THPT,Miền Nam,"[Vật lý, Hóa học]","[Toán (Đại số / Giải tích), Toán (Hình học), T...",[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn"";Thứ hạng ư...",NaN,True
6,2026/03/26 12:43:13 CH GMT+7,Lớp 10,Miền Bắc,"[Hóa học, Sinh học]","[Toán (Đại số / Giải tích), Toán (Hình học), N...",[8.0 - 9.0),A00,[27 - 30),Khác,Thứ hạng ước tính;Phân tích phổ điểm,Muốn biết có đứng top 10 toàn quốc không?,True
7,2026/03/26 1:59:22 CH GMT+7,Đã tốt nghiệp THPT,Miền Nam,[],"[Toán (Đại số / Giải tích), Toán (Hình học), N...",[6.0 - 7.0),"A01,C01",[18 - 21),Xét tuyển bằng điểm thi THPTQG,"Xác suất ""an toàn""",NaN,True
8,2026/03/26 7:19:06 CH GMT+7,Đã tốt nghiệp THPT,Miền Nam,"[Toán (Đại số / Giải tích), Vật lý, Tin học]",[Tiếng Anh],[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Xác suất ""an toàn""",Có,True
9,2026/03/26 7:33:47 CH GMT+7,Đã tốt nghiệp THPT,Miền Nam,"[Toán (Đại số / Giải tích), Toán (Hình học), N...","[Toán (Đại số / Giải tích), Toán (Hình học), T...",[8.0 - 9.0),"B00, D01",[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn"";So sánh tổ...",NaN,False

## Tổ hợp

In [16]:
bang_to_hop = pd.read_csv("input/bang_to_hop_mon.csv")

mapping_to_hop = {}
for _, row in bang_to_hop.iterrows():
    mapping_to_hop[row['Tổ hợp']] = {row['Môn 1'], row['Môn 2'], row['Môn 3']}

In [17]:
# Quy các môn Toán về cùng 1 môn

subject_mapping = {
    "Toán (Đại số / Giải tích)": "Toán",
    "Toán (Hình học)": "Toán",
    "Ngữ văn": "Văn",
    "Tiếng Anh": "Anh",
    "Vật lý": "Lý",
    "Hóa học": "Hóa",
    "Sinh học": "Sinh",
    "Lịch sử": "Sử",
    "Địa lý": "Địa",
    "GDKT&PL (hoặc Giáo dục công dân)": "Giáo dục kinh tế và pháp luật",
    "Tin học": "Tin"
    # Hai môn Công nghệ giữ nguyên nên không cần map
}

def collapse_subjects(subject_list):
    # Chuyển đổi và dùng set() để loại bỏ trùng lặp 
    # (Tránh việc một dòng có cả Đại và Hình sẽ bị biến thành ['Toán', 'Toán'])
    collapsed = {subject_mapping.get(s, s) for s in subject_list}
    
    return list(collapsed)

# Áp dụng cho cả 2 cột
clean_df["mon_gioi"] = clean_df["mon_gioi"].apply(collapse_subjects)
clean_df["mon_yeu"] = clean_df["mon_yeu"].apply(collapse_subjects)

In [18]:
import re

def extract_combinations(text):
    if pd.isna(text):
        return []
    
    # 1. Chuyển về chữ thường để dễ xử lý
    text = str(text).lower()
    
    # 2. Dùng Regex để tìm các mã khối (Ví dụ: a00, b01, d07...)
    # Pattern: 1 chữ cái + 2 hoặc 3 chữ số
    codes = re.findall(r'[a-z]\d{2,3}', text)
    
    # 3. Chuẩn hóa về chữ hoa
    valid_codes = [c.upper() for c in codes]
    
    # Nếu không tìm thấy mã khối nào, trả về ['INVALID'] để sau này lọc bỏ
    return valid_codes if valid_codes else ["INVALID"]


col_name = 'to_hop_du_dinh'
clean_df['to_hop_clean'] = clean_df[col_name].apply(extract_combinations)

In [19]:
def check_target_logic(row):
    if not row["valid"]: 
        return False
    
    user_combos = row["to_hop_clean"]
    mon_gioi = set(row["mon_gioi"])
    if not mon_gioi:
        return True
    
    for combo in user_combos:
        if combo in mapping_to_hop:
            # Nếu mục tiêu là combo này, nhưng mon_gioi không chứa môn nào trong đó
            if not (mon_gioi & mapping_to_hop[combo]):
                return False
    return True

clean_df["valid"] = clean_df.apply(check_target_logic, axis=1)

In [20]:
clean_df.head(10)

,Dấu thời gian,doi_tuong,dia_diem,mon_gioi,mon_yeu,diem_gan_nhat,to_hop_du_dinh,diem_du_doan,muc_dich,muc_tieu_chinh,muc_tieu_phu,valid,to_hop_clean
0,2026/03/24 7:09:52 CH GMT+7,Lớp 12,Miền Nam,[],[],[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn""",NaN,True,[A00]
1,2026/03/24 10:27:40 CH GMT+7,Lớp 11,Miền Nam,[],[],[8.0 - 9.0),A01,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn"";So sánh tổ...",em mong muốn được vỡ oà cảm xúc sau những chặn...,True,[A01]
2,2026/03/24 10:28:35 CH GMT+7,Lớp 12,Miền Nam,[],[],[8.0 - 9.0),D01 A01,[18 - 21),Xét tuyển bằng điểm thi THPTQG,"Xác suất ""an toàn""",Biết mình đậu hay ki,True,"[D01, A01]"
3,2026/03/25 5:50:08 CH GMT+7,Đã tốt nghiệp THPT,Miền Trung,[],[],[9.0 - 10.0],A00,[27 - 30),Lấy điểm để đi du học hoặc xét tuyển riêng.,Phân tích phổ điểm,Nụ cười của cha mẹ,True,[A00]
4,2026/03/26 11:29:09 SA GMT+7,Đã tốt nghiệp THPT,Miền Trung,"[Toán, Hóa]","[Văn, Anh, Sinh]",[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,Phân tích phổ điểm;So sánh tổ hợp,NaN,True,[A00]
5,2026/03/26 11:40:45 SA GMT+7,Đã tốt nghiệp THPT,Miền Nam,"[Lý, Hóa]","[Toán, Anh]",[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn"";Thứ hạng ư...",NaN,True,[A00]
6,2026/03/26 12:43:13 CH GMT+7,Lớp 10,Miền Bắc,"[Hóa, Sinh]","[Sử, Văn, GDKT&PL (Hoặc GDCD), Công nghệ công ...",[8.0 - 9.0),A00,[27 - 30),Khác,Thứ hạng ước tính;Phân tích phổ điểm,Muốn biết có đứng top 10 toàn quốc không?,True,[A00]
7,2026/03/26 1:59:22 CH GMT+7,Đã tốt nghiệp THPT,Miền Nam,[],"[Toán, Văn, Lý, Anh]",[6.0 - 7.0),"A01,C01",[18 - 21),Xét tuyển bằng điểm thi THPTQG,"Xác suất ""an toàn""",NaN,True,"[A01, C01]"
8,2026/03/26 7:19:06 CH GMT+7,Đã tốt nghiệp THPT,Miền Nam,"[Toán, Lý, Tin]",[Anh],[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Xác suất ""an toàn""",Có,True,[A00]
9,2026/03/26 7:33:47 CH GMT+7,Đã tốt nghiệp THPT,Miền Nam,"[Sinh, Văn, Lý, Anh, Hóa, Toán]","[Toán, Anh, Hóa, Sinh]",[8.0 - 9.0),"B00, D01",[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn"";So sánh tổ...",NaN,False,"[B00, D01]"

# Xử lý mong muốn chính

In [21]:
valid_targets = [
    "Vị thế tương đối", 
    "Xác suất \"an toàn\"", 
    "Thứ hạng ước tính", 
    "Phân tích phổ điểm", 
    "So sánh tổ hợp"
]

def process_multi_choice_target(text):
    if pd.isna(text): return []
    
    # Tách các lựa chọn dựa trên dấu phẩy
    choices = [c.strip() for c in str(text).split(';')]
    
    final_choices = []
    has_junk = False
    
    for c in choices:
        if c in valid_targets:
            final_choices.append(c)
        else:
            # Đây là phần "điền tay"
            # Nếu điền tay mà có nghĩa (độ dài > 5 và không phải ký tự rác)
            if len(c) > 5 and not any(char in c for char in [".", "x", "asdf"]):
                final_choices.append("Custom: " + c)
            else:
                has_junk = True # Dính bẫy điền bừa
                
    return final_choices, has_junk

# Áp dụng
res = clean_df.iloc[:, 9].apply(process_multi_choice_target)
clean_df['target_list'] = res.apply(lambda x: x[0])
clean_df['hit_target_trap'] = res.apply(lambda x: x[1])

# Nếu dính bẫy (điền tay rác rưởi) thì đánh dấu invalid
clean_df.loc[clean_df['hit_target_trap'], 'valid'] = False

# Xử lý mong muốn phụ

In [22]:
def clean_khao_khat(text):
    if pd.isna(text):
        return None
    
    # Chuẩn hóa: viết thường, bỏ khoảng trắng thừa
    t = str(text).lower().strip(";")
    
    # 1. Danh sách các câu trả lời "vô thưởng vô phạt"
    blacklist = [
        'không', 'không có', 'không có mong muốn nào khác', 'không còn', 
        'ko', 'k', 'khong', 'khônng', 'khômg', 'none', 'no', 'k bít', 'ko biết', 
        'không biết', 'không ạ', 'em không muốn trả lời ạ...', 'chưa có',
        'chúc anh chị thi vào ngôi trường đại học mà mình mong muốn!!', # Câu chúc, không phải mong muốn bản thân
        'dạ em không có ý kiến..', 'không viết', 'ngủ', 'nghỉ hè'
    ]
    
    # 2. Lọc theo danh sách đen
    if t in blacklist:
        return None
    
    # 3. Lọc theo độ dài và ký tự rác (như "shbsbaah", "..", "^^")
    if len(t) < 3 or t.startswith('^^') or t.startswith('..'):
        return None
        
    # Nếu vượt qua các bộ lọc trên, trả về nội dung gốc (đã strip)
    return str(text).strip()

# Áp dụng
clean_df['khao_khat_clean'] = clean_df.iloc[:, 10].apply(clean_khao_khat)

In [23]:
clean_df.head()

,Dấu thời gian,doi_tuong,dia_diem,mon_gioi,mon_yeu,diem_gan_nhat,to_hop_du_dinh,diem_du_doan,muc_dich,muc_tieu_chinh,muc_tieu_phu,valid,to_hop_clean,target_list,hit_target_trap,khao_khat_clean
0,2026/03/24 7:09:52 CH GMT+7,Lớp 12,Miền Nam,[],[],[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn""",NaN,True,[A00],"[Vị thế tương đối, Xác suất ""an toàn""]",False,NaN
1,2026/03/24 10:27:40 CH GMT+7,Lớp 11,Miền Nam,[],[],[8.0 - 9.0),A01,[24 - 27),Xét tuyển bằng điểm thi THPTQG,"Vị thế tương đối;Xác suất ""an toàn"";So sánh tổ...",em mong muốn được vỡ oà cảm xúc sau những chặn...,True,[A01],"[Vị thế tương đối, Xác suất ""an toàn"", So sánh...",False,em mong muốn được vỡ oà cảm xúc sau những chặn...
2,2026/03/24 10:28:35 CH GMT+7,Lớp 12,Miền Nam,[],[],[8.0 - 9.0),D01 A01,[18 - 21),Xét tuyển bằng điểm thi THPTQG,"Xác suất ""an toàn""",Biết mình đậu hay ki,True,"[D01, A01]","[Xác suất ""an toàn""]",False,Biết mình đậu hay ki
3,2026/03/25 5:50:08 CH GMT+7,Đã tốt nghiệp THPT,Miền Trung,[],[],[9.0 - 10.0],A00,[27 - 30),Lấy điểm để đi du học hoặc xét tuyển riêng.,Phân tích phổ điểm,Nụ cười của cha mẹ,True,[A00],[Phân tích phổ điểm],False,Nụ cười của cha mẹ
4,2026/03/26 11:29:09 SA GMT+7,Đã tốt nghiệp THPT,Miền Trung,"[Toán, Hóa]","[Văn, Anh, Sinh]",[8.0 - 9.0),A00,[24 - 27),Xét tuyển bằng điểm thi THPTQG,Phân tích phổ điểm;So sánh tổ hợp,NaN,True,[A00],"[Phân tích phổ điểm, So sánh tổ hợp]",False,NaN

In [24]:
# Đếm số lượng True/False trong cột valid
stats = clean_df['valid'].value_counts()

# Tính tỷ lệ %
total = len(clean_df)
true_count = stats.get(True, 0)
false_count = stats.get(False, 0)

print("--- BÁO CÁO CHẤT LƯỢNG DỮ LIỆU ---")
print(f"✅ Hợp lệ (True):  {true_count} dòng ({true_count/total:.2%})")
print(f"❌ Bị loại (False): {false_count} dòng ({false_count/total:.2%})")
print(f"📊 Tổng cộng:      {total} dòng")

--- BÁO CÁO CHẤT LƯỢNG DỮ LIỆU ---
✅ Hợp lệ (True):  209 dòng (70.37%)
❌ Bị loại (False): 88 dòng (29.63%)
📊 Tổng cộng:      297 dòng

In [26]:
# 1. Lọc lấy 202 dòng sạch
df_final = clean_df[clean_df["valid"] == True].copy()

# 2. Danh sách các cột "vàng" cần giữ lại để làm Dashboard/Tiểu luận
selected_columns = [
    'Dấu thời gian', 
    'doi_tuong', 
    'dia_diem', 
    'mon_gioi', 
    'mon_yeu', 
    'diem_gan_nhat', 
    'to_hop_du_dinh', 
    'to_hop_clean',    # Cột đã qua Regex
    'diem_du_doan', 
    'muc_dich', 
    'target_list',     # Cột đã tách list
    'khao_khat_clean' # Cột khao khát đã lọc None
]

# 3. Lưu file
df_final[selected_columns].to_csv("output/survey_cleaned_final.csv", index=False, encoding='utf-8-sig')

print("Đã lưu 209 dòng 'vàng' vào file survey_cleaned_final.csv!")

Đã lưu 209 dòng 'vàng' vào file survey_cleaned_final.csv!